Set up flutter testing
MartinBruun/P6 pull request #245
Opened 2022-04-29 12:56 UTC by Rallefar1103

2022-04-29 19:54 UTC, MartinBruun requested changes
CI fejler. Ser ud til der er nogle steder hvor "await Future(test.main);" er undefined, men kan ikke se det i din kode hvor det skulle være?

Har du pushet alt du har locally op på github?

2022-04-30 10:01 UTC, MartinBruun requested changes
Tilføj tests eller slet sign_in_test.dart og sign_out_test.dart (kan desværre ikke markere de filer seperat, da de er tomme....)

Har sat en del kommentarer. Det er op til dig at vurdere hvorvidt du ønsker at følge dem, men det ville være fedt hvis du læser det, da vi så har noget at diskutere om ;)

Det er vigtigt for mig at sige, at det er super fedt arbejde! Det er super nemt at læse testene, de er korte og to the point, hvilket gør at jeg kan skrive de kritiske kommentarer jeg kan. Det er mest et spørgsmål om at der er en del som er meget implicit i testene sådan som de står nu, hvilket gjorde jeg skulle scrolle meget op og ned, og blev forvirret undervejs.

2022-04-30 10:01 UTC, MartinBruun commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +    repositoryImpl = GetMachinesRepositoryImpl(
Generelt, gør det gerne for alle navnene, så mockCommunicator => mockWebCommunicator
Ligesom du har gjort med NetworkInfo!

2022-04-30 11:16 UTC, MartinBruun commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +      expect(result, new List.empty());
PS: Har nok ændret mening. Synes det giver mening at WidgetTests mocker UseCase

IntegrationTests er dem som laver en "hel bruger oplevelse", og dermed kun mocker Communicator delen.

Reele tests af om det virker (hvor der bliver kaldt de forskellige andre containers) burde være nogle "User Story tests" som egentlig ligger udenfor washee_app, washee_web og washee_box, da det er en test af integration af alle delene. Disse test ville så blive skrevet i det som useren i den givne user story direkte interagere med (i vores tilfælde ville det alt sammen være skrevet i flutter, da users kun bruger det. Men senere kunne nogle blive skrevet i python, givet hjemmesiden måske kunne være der en evt. bygningsejer ville gå ind og hente data/se regnskab/ etc.)

2022-04-30 11:20 UTC, MartinBruun commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +      expect(result, new List.empty());
Ved at WidgetTests mocker UseCase får vi også et meget clean design:

Alle tests:
Mocker Log (og andre "side effects" der kommer fra core modulet)

Unit tests:
Widget mocker Usecase
Usecase mocker Repository
Repository mocker Remote
Remote mocker Communicator (IKKE manageren! mock af communicator => mock af dio i vores tilfælde!)

Integration tests:
Mocker kun Communicators, så vi kan se det altsammen integreres ordentligt

User Story Tests
Mocker ingenting. Starter alle containers og laver "live" testing af et lukket system (simulerer en "historie" af hvordan nogle brugere agere) som bagefter blive lukket og får slette alle data bagefter.

2022-04-30 11:21 UTC, MartinBruun commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +      expect(result, new List.empty());
damn det blev langt. Beklager du skal læse igennem alt det her xD

2022-04-30 11:22 UTC, MartinBruun commented
Det er VIGTIGT der ikke bliver merged før vi i det mindste lige har fået snakket om det her! Nogle af tingene kan vi godt blive enige om, men så oprettes de som issues der skal håndteres senere.

2022-04-30 11:50 UTC, Rallefar1103 commented on washee_app/lib/features/get_machines/presentation/widgets/machine_overview.dart
> +                      key: Key('machines-progress-indicator'),
Key'en er en reference til den specifikke widget i widget-træet. 
Når man widget tester så kan man finde en widget enten byWidget, byType eller byKey. Og byKey er mest unikt :-)

2022-04-30 11:51 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +    mockMachines = listOfMockMachines();
fakes kan vi godt kalde det.

2022-04-30 11:54 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +      expect(result, new List.empty());
den burde nok returnere null istedet. Kan sgu ikke huske hvorfor det blev en empty list.

2022-04-30 11:57 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/data/repositories/get_machines_repo_impl_test.dart
> +    'should call the WebCommunicator and return a list of machine models',
Jamen testene herinde er jo alle for getMachineRepositoryImpl - så det er rimelig implicit at det naturligvis er DET repository der bør kalde webcommunicator.

Og nej det er ikke remoten, for den har ingen remote - hvilket nok er forkert, men mindes det var noget af det aller første der blev lavet så det blev bikset sammen lidt hurtigt :-) ellers har du ret.

2022-04-30 11:57 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/presentation/pages/wash_screen_test.dart
> +      await tester.pumpWidget(createWidgetUnderTest());
kig i funktionen. Den mocker usecasen som den her widget depender på :-)

2022-04-30 11:59 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/presentation/pages/wash_screen_test.dart
> +      await tester.pump(const Duration(milliseconds: 500));
Det her var standard måden at gøre det på - så jeg fulgte blot anvisningen.

2022-04-30 12:00 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/presentation/pages/wash_screen_test.dart
> +        await tester.pumpAndSettle();
Fordi vi ikke er interreseret i at fange nogle circular progress indicator. Her skal vi bare have resultatet ud instantly.

2022-04-30 12:01 UTC, Rallefar1103 commented on washee_app/test/features/washee_service/presentation/pages/wash_screen_test.dart
> +    testWidgets("Machines are displayed after successfull backend fetch",
Kan ikke forstå du skal lede efter hvilken widget der er under test. Det står i test navnet :-) WashScreen.

2022-05-01 12:00 UTC, MartinBruun approved these changes
Småting jeg nok selv ville gøre lidt anderledes, men grundlæggende et godt udgangspunkt for fremtidig test!

2022-05-01 12:00 UTC, merged